// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_ins module generated by `tlgen.py` tool
// all reset signals should be generated from one reset signal to not make any deadlock
//
// Interconnect
// ibex_ins
//   -> s1n_3
//     -> sram_ins
//     -> dbg_dev

module xbar_ins (
  input clk_sys_i,
  input rst_sys_ni,

  // Host interfaces
  input  tlul_pkg::tl_h2d_t tl_ibex_ins_i,
  output tlul_pkg::tl_d2h_t tl_ibex_ins_o,

  // Device interfaces
  output tlul_pkg::tl_h2d_t tl_sram_ins_o,
  input  tlul_pkg::tl_d2h_t tl_sram_ins_i,
  output tlul_pkg::tl_h2d_t tl_dbg_dev_o,
  input  tlul_pkg::tl_d2h_t tl_dbg_dev_i,

  input prim_mubi_pkg::mubi4_t scanmode_i
);

  import tlul_pkg::*;
  import tl_ins_pkg::*;

  // scanmode_i is currently not used, but provisioned for future use
  // this assignment prevents lint warnings
  logic unused_scanmode;
  assign unused_scanmode = ^scanmode_i;

  tl_h2d_t tl_s1n_3_us_h2d ;
  tl_d2h_t tl_s1n_3_us_d2h ;


  tl_h2d_t tl_s1n_3_ds_h2d [2];
  tl_d2h_t tl_s1n_3_ds_d2h [2];

  // Create steering signal
  logic [1:0] dev_sel_s1n_3;



  assign tl_sram_ins_o = tl_s1n_3_ds_h2d[0];
  assign tl_s1n_3_ds_d2h[0] = tl_sram_ins_i;

  assign tl_dbg_dev_o = tl_s1n_3_ds_h2d[1];
  assign tl_s1n_3_ds_d2h[1] = tl_dbg_dev_i;

  assign tl_s1n_3_us_h2d = tl_ibex_ins_i;
  assign tl_ibex_ins_o = tl_s1n_3_us_d2h;

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_3 = 2'd2;
    if ((tl_s1n_3_us_h2d.a_address &
         ~(ADDR_MASK_SRAM_INS)) == ADDR_SPACE_SRAM_INS) begin
      dev_sel_s1n_3 = 2'd0;

    end else if ((tl_s1n_3_us_h2d.a_address &
                  ~(ADDR_MASK_DBG_DEV)) == ADDR_SPACE_DBG_DEV) begin
      dev_sel_s1n_3 = 2'd1;
end
  end


  // Instantiation phase
  tlul_socket_1n #(
    .HReqDepth (4'h0),
    .HRspDepth (4'h0),
    .DReqDepth (8'h0),
    .DRspDepth (8'h0),
    .N         (2)
  ) u_s1n_3 (
    .clk_i        (clk_sys_i),
    .rst_ni       (rst_sys_ni),
    .tl_h_i       (tl_s1n_3_us_h2d),
    .tl_h_o       (tl_s1n_3_us_d2h),
    .tl_d_o       (tl_s1n_3_ds_h2d),
    .tl_d_i       (tl_s1n_3_ds_d2h),
    .dev_select_i (dev_sel_s1n_3)
  );

endmodule
